<a href="https://colab.research.google.com/github/Dwayne-tech/DML/blob/main/Python_Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
import numpy as np
#Create Arrays
array_1d= np.array([0,1,2,3,4,5,6,7,8,9])
print(array_1d)
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_2d)

#Array Indexing and Slicing
#Access the 5th element of the 1D array created earlier.
index_fifth_number = array_1d[5]
print(index_fifth_number)

#Access the element at row 2, column 3 of the 3x3 array.
row_2_column_3 = array_2d[1,:3]
print(row_2_column_3)

#Slice the 1D array to extract values from index 3 to 7.
slice_array = array_1d[3:8]
print(slice_array)

#Slice the 3x3 array to extract the second row.
slice_array = array_2d[1,:]
print(slice_array)

#Array Operations
#Multiply all elements in the 1D array by 2.
array_3d = array_1d*2
print(array_3d)

#Add 10 to all elements in the 3x3 array.
add_array_2d = array_2d + 10
print(add_array_2d)

#Find the sum of all elements in the 1D array.
sum_1d_array =  np.sum(array_1d)
print(sum_1d_array)

#Find the mean of all elements in the 3x3 array.
mean_array_2d = np.mean(array_2d)
print(mean_array_2d)

#Mathematical Functions
#Generate a NumPy array of 10 evenly spaced values between 0 and 1
array_evenly_spaced = np.linspace(0,1,10)
print(array_evenly_spaced)

#Create a 1D array with 10 random integers between 1 and 50.
array_random_1d = np.random.randint(1,50,10)
print(array_random_1d)

#Find the maximum and minimum values from the random array.
max_array_random_1d = np.max(array_random_1d)
min_array_random_1d = np.min(array_random_1d)
print(max_array_random_1d)
print(min_array_random_1d)

#Calculate the standard deviation of the random array.
std_array_random_1d = np.std(array_random_1d) # Assign to a new variable to avoid overwriting
print(std_array_random_1d)

#Reshaping Arrays
#Reshape the 1D array of random integers into a 2D array (2x5).
array_reshape = array_random_1d.reshape(2,5)
print(array_reshape)

#Transpose the reshaped array.
transpose_array= np.transpose(array_reshape)
print(transpose_array)

#Logical Operations
#Create a boolean mask where elements in the 1D array of random integers are greater than 25
boolean_mask = array_random_1d > 25
print(boolean_mask)

#Use this mask to filter the elements in the array that are greater than 25.
filter_array = array_random_1d[boolean_mask]
print(filter_array)

# Bonus Challenge
#Create a 4x4 identity matrix using NumPy.
import numpy as np
identity_matrix = np.identity(4)

print(identity_matrix)

#Create a diagonal matrix with values 1, 2, 3, 4 along its diagonal.
diagonal_matrix = np.diag([1,2,3,4])
print(diagonal_matrix)



[0 1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
[4 5 6]
[3 4 5 6 7]
[4 5 6]
[ 0  2  4  6  8 10 12 14 16 18]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
45
5.0
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[24 45 11 19  4 12 36 49 29 21]
49
4
14.042791745233567
[[24 45 11 19  4]
 [12 36 49 29 21]]
[[24 12]
 [45 36]
 [11 49]
 [19 29]
 [ 4 21]]
[False  True False False False False  True  True  True False]
[45 36 49 29]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
